---
Name: contacts-routes
After:
  - '#rootroutes'
  - '#coreroutes'
---

SilverStripe\Control\Director:
  rules:
    'contacts-api/address//$Action': 'Clesson\Contacts\Controllers\AddressController'
    'contact//$Action/$Slug': 'Clesson\Contacts\Controllers\ContactController'
